### ISSUE TITLE
malloc without free

### ISSUE THREAD

**Issue by reqshark** [fatihky/framer#2]
overall framer c looks like very good implementation IMO.  Very fast.

One thing, there is [a call to malloc here](https://github.com/fatihky/framer/blob/ea81a1c382fa4a000fe8e236cf718dac506d3fe5/c/src/framer.c#L85), and I'm not seeing where this memory gets freed.

**Comment by reqshark** [comment]
also I wonder whether this is a good case for `alloca()` ?

**Comment by fatihky** [comment]
There are a bad implementation. Here parser creates copy of frame and adds it to `in_frames` list.  https://github.com/fatihky/framer/blob/ea81a1c382fa4a000fe8e236cf718dac506d3fe5/c/src/framer.c#L99-L112

**Comment by fatihky** [comment]
I am returning that allocated chunk to the user. And user can free that chunk with frm_frame_term or frm_frame_destroy.
